Add cover letter functionality
feder-cr/Auto_Jobs_Applier_AIHawk pull request #628
Opened 2024-10-27 19:15 UTC by yusefes

Fixes #614

Add functionality to specify a specific cover letter for job applications.

* **main.py**
  - Add `cover_letter` option to the `main` function to specify a cover letter file.
  - Update `FileManager.file_paths_to_dict` method to handle the `cover_letter` file.
  - Pass the `cover_letter` file to the `create_and_run_bot` function.

* **src/aihawk_easy_applier.py**
  - Update `_handle_upload_fields` method to handle the `cover_letter` file.
  - Add logic to upload cover letter from the specified path if it exists.

* **src/job_application_profile.py**
  - Add `cover_letter` attribute to the `JobApplicationProfile` class.
  - Update `__init__` method to initialize the `cover_letter` attribute.

* **data_folder_example/plain_text_resume.yaml**
  - Add `cover_letter` field with example content.

* **data_folder/plain_text_resume.yaml**
  - Add `cover_letter` field.

---

For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/feder-cr/Auto_Jobs_Applier_AIHawk/issues/614?shareId=b4ec2c66-5d15-4e31-891c-7601b82ce8e7).

2024-10-28 00:14 UTC, surapuramakhil commented on src/aihawk_easy_applier.py
> +                if job.cover_letter_path is not None and os.path.exists(job.cover_letter_path):
move this check to method something like  if_coverletter_exits or something silimar. method name should be check objective.

2024-10-28 00:17 UTC, surapuramakhil commented on main.py
> +    def file_paths_to_dict(resume_file: Path | None, plain_text_resume_file: Path, cover_letter_file: Path | None = None) -> dict:
Boy Scout Code Principle

Can you move FileManager to a different file maybe file_manager.py

rename method file_paths_to_dict to something meaning full. refactor method if possible

2024-10-28 00:24 UTC, surapuramakhil commented on src/job_application_profile.py
> +        # Process cover_letter
Appriciate if you can refactor the code - DRY principle

you see code patterns are repeated. can you remove those repeated code patterns using method calls

2024-10-28 00:26 UTC, surapuramakhil commented on src/aihawk_easy_applier.py
> +                if job.cover_letter_path is not None and os.path.exists(job.cover_letter_path):
I guess you are missing case where cover is in plain text resume.yaml

2024-10-28 00:28 UTC, surapuramakhil requested changes
this one is important - https://github.com/feder-cr/Auto_Jobs_Applier_AIHawk/pull/628/files#r1818228664

Other requests are for improving this code base. Appricate if those were addressed.

@yusefes good work

2024-10-29 00:56 UTC, feder-cr commented
@yusefes resolve the conflicts

2024-10-31 20:47 UTC, closed without merging