Add automated error capturing with video
feder-cr/Auto_Jobs_Applier_AIHawk pull request #629
Opened 2024-10-27 19:17 UTC by yusefes

Fixes #618

Add automated error capturing with video recording.

* Add `opencv-python` to `requirements.txt` for video recording.
* Add `capture_error` function in `src/utils.py` to handle error capturing and video recording.
* Update `main.py` to call `capture_error` in exception handling blocks.
* Update `src/aihawk_easy_applier.py` to call `capture_error` in exception handling blocks.
* Update `src/aihawk_job_manager.py` to call `capture_error` in exception handling blocks.

---

For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/feder-cr/Auto_Jobs_Applier_AIHawk/issues/618?shareId=f2ee2ede-9d3e-4f9f-842a-03c6c96da9f3).

2024-10-29 22:35 UTC, surapuramakhil requested changes
if possible, can you create screen_record_utils.py and move screen recording code over there.

Also create error_utils.py

2024-10-29 22:35 UTC, surapuramakhil commented on src/utils.py
> +    # Record a video of the browser screen
move line 187 to 196 to separate method - call it as record browser screen, you  can have time as param (up to you)

2024-10-29 22:35 UTC, surapuramakhil commented on src/utils.py
> +    screenshot_path = os.path.join(error_dir, "screenshot.png")
move this to separate method - capture_browser_screenhot

2024-10-29 22:36 UTC, surapuramakhil commented
@yusefes great work.

2024-10-29 22:37 UTC, surapuramakhil commented
@yusefes also this PR has failed in some testcases - can you also fix text cases before you push your changes.

2024-10-31 20:47 UTC, closed without merging

2024-11-06 16:37 UTC, surapuramakhil commented
@yusefes very unfortunate you closed this PR.

2024-11-19 23:48 UTC, feder-cr commented
@yusefes Hi, do you want to work on this?

For better communication with other open source developers I suggest you join our discord group: https://discord.gg/mMZcMTH9K6